# Generated by Django 5.0 on 2024-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_inicial",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("imagen", models.FileField(upload_to="")),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("fecha_inicio",),
            },
        ),
    ]
