# Generated by Django 5.0 on 2024-09-30 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anuncio", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="anuncio",
            name="publicado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anuncios_publicados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anuncio",
            name="categorias",
            field=models.ManyToManyField(to="anuncio.categoria"),
        ),
        migrations.CreateModel(
            name="OfertaAnuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_oferta", models.DateTimeField(auto_now_add=True)),
                ("precio_oferta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("es_ganador", models.BooleanField(default=False)),
                (
                    "anuncio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="anuncio.anuncio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="anuncio",
            name="oferta_ganadora",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oferta_ganadora",
                to="anuncio.ofertaanuncio",
            ),
        ),
        migrations.CreateModel(
            name="SeguimientoAnuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now=True)),
                (
                    "anuncio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="anuncio.anuncio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos_anuncios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
