# Generated by Django 5.0 on 2024-10-07 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anuncio", "0003_categoria_alter_anuncio_publicado_por_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncio",
            name="fecha_inicio",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
